const root=document.documentElement.dataset.root||'',page=document.documentElement.dataset.page;
let session=JSON.parse(localStorage.getItem('jalancareSession')||sessionStorage.getItem('jalancareSession')||'null');
if(!session) location.replace(root+'index.html');
const role=session?.role||'Pemohon',isAdmin=role==='Pentadbir';
const pages={dashboard:['Papan Pemuka','Ringkasan operasi penyelenggaraan jalan'], 'permohonan-baru':['Permohonan Baharu','Daftarkan kerosakan dan cadangan tindakan'], 'permohonan-senarai':['Senarai Permohonan','Cari, tapis dan pantau semua permohonan'],semakan:['Semakan Teknikal','Penilaian tapak, kerosakan dan skop kerja'],kelulusan:['Kelulusan','Semak cadangan kos dan buat keputusan'],pelaksanaan:['Pelaksanaan Kerja','Pantau jadual dan kemajuan kerja'],pengesahan:['Pengesahan Siap','Periksa hasil kerja sebelum penutupan'],laporan:['Laporan & Analisis','Prestasi, kos dan trend penyelenggaraan'],'pengguna-senarai':['Pengurusan Pengguna','Akaun, peranan dan status akses'],'pengguna-baharu':['Cipta Pengguna Baharu','Daftarkan akaun dan tentukan peranan'],panduan:['Panduan Sistem','Aliran kerja dan penggunaan setiap modul'],profil:['Profil Saya','Maklumat akaun dan keselamatan']} ;
const roleAccess={
  Pemohon:['dashboard','permohonan-baru','permohonan-senarai','panduan','profil'],
  Juruteknik:['dashboard','permohonan-senarai','semakan','pelaksanaan','laporan','panduan','profil'],
  'Jurutera Daerah':['dashboard','permohonan-senarai','semakan','kelulusan','pelaksanaan','pengesahan','laporan','panduan','profil'],
  'Pegawai Pelaksana':['dashboard','permohonan-senarai','pelaksanaan','panduan','profil'],
  'Pegawai Pengesah':['dashboard','permohonan-senarai','pengesahan','panduan','profil'],
  Pemerhati:['dashboard','permohonan-senarai','pelaksanaan','pengesahan','laporan','panduan','profil'],
  Pentadbir:['dashboard','permohonan-baru','permohonan-senarai','semakan','kelulusan','pelaksanaan','pengesahan','laporan','pengguna-senarai','pengguna-baharu','panduan','profil']
};
const allowed=roleAccess[role]||roleAccess.Pemohon;if(!allowed.includes(page)){alert('Anda tidak mempunyai kebenaran untuk mengakses modul ini.');location.replace(root+'dashboard.html')}
const roleMenus={
  Pemohon:[['Utama',[['dashboard','⌂','Papan Pemuka Saya','dashboard.html']]],['Permohonan Saya',[['permohonan-baru','＋','Permohonan Baharu','permohonan/baru.html'],['permohonan-senarai','▤','Status Permohonan','permohonan/senarai.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  Juruteknik:[['Utama',[['dashboard','⌂','Papan Pemuka Teknikal','dashboard.html']]],['Pemeriksaan',[['permohonan-senarai','▤','Tugasan Pemeriksaan','permohonan/senarai.html'],['semakan','⌕','Semakan Teknikal','semakan/index.html']]],['Pemantauan',[['pelaksanaan','⚒','Status Pelaksanaan','pelaksanaan/index.html'],['laporan','▥','Laporan Teknikal','laporan/index.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  'Jurutera Daerah':[['Utama',[['dashboard','⌂','Papan Pemuka Kelulusan','dashboard.html']]],['Semakan & Kelulusan',[['permohonan-senarai','▤','Semua Permohonan','permohonan/senarai.html'],['semakan','⌕','Semakan Teknikal','semakan/index.html'],['kelulusan','✓','Menunggu Kelulusan','kelulusan/index.html']]],['Pemantauan',[['pelaksanaan','⚒','Pelaksanaan Kerja','pelaksanaan/index.html'],['pengesahan','◎','Pengesahan Siap','pengesahan/index.html'],['laporan','▥','Laporan Pengurusan','laporan/index.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  'Pegawai Pelaksana':[['Utama',[['dashboard','⌂','Papan Pemuka Pelaksanaan','dashboard.html']]],['Arahan Kerja',[['permohonan-senarai','▤','Kerja Ditugaskan','permohonan/senarai.html'],['pelaksanaan','⚒','Kemas Kini Kemajuan','pelaksanaan/index.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  'Pegawai Pengesah':[['Utama',[['dashboard','⌂','Papan Pemuka Pengesahan','dashboard.html']]],['Pemeriksaan Siap',[['permohonan-senarai','▤','Menunggu Pemeriksaan','permohonan/senarai.html'],['pengesahan','◎','Pengesahan Siap','pengesahan/index.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  Pemerhati:[['Utama',[['dashboard','⌂','Papan Pemuka Pengurusan','dashboard.html']]],['Pemantauan',[['permohonan-senarai','▤','Status Keseluruhan','permohonan/senarai.html'],['pelaksanaan','⚒','Prestasi Pelaksanaan','pelaksanaan/index.html'],['pengesahan','◎','Rekod Pengesahan','pengesahan/index.html']]],['Analisis',[['laporan','▥','Laporan Pengurusan','laporan/index.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]],
  Pentadbir:[['Utama',[['dashboard','⌂','Papan Pemuka Sistem','dashboard.html']]],['Operasi',[['permohonan-baru','＋','Permohonan Baharu','permohonan/baru.html'],['permohonan-senarai','▤','Semua Permohonan','permohonan/senarai.html'],['semakan','⌕','Semakan Teknikal','semakan/index.html'],['kelulusan','✓','Kelulusan','kelulusan/index.html'],['pelaksanaan','⚒','Pelaksanaan','pelaksanaan/index.html'],['pengesahan','◎','Pengesahan Siap','pengesahan/index.html'],['laporan','▥','Laporan Sistem','laporan/index.html']]],['Pentadbiran',[['pengguna-senarai','♙','Pengurusan Pengguna','pengguna/senarai.html'],['pengguna-baharu','⊕','Cipta Pengguna','pengguna/baharu.html']]],['Bantuan',[['panduan','?','Panduan Sistem','panduan/index.html'],['profil','♢','Profil Saya','profil/index.html']]]]
};
const nav=(roleMenus[role]||roleMenus.Pemohon).map(g=>`<div class="nav-group"><span class="nav-label">${g[0]}</span>${g[1].map(i=>`<a class="${page===i[0]?'active':''}" href="${root+i[3]}" title="${i[2]}"><span class="nav-icon">${i[1]}</span><span class="nav-text">${i[2]}</span></a>`).join('')}</div>`).join('');
const badge='<a class="visitor-badge" href="https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2Fdrshahizan" target="_blank" rel="noopener noreferrer"><img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2Fdrshahizan&amp;labelColor=%23697689&amp;countColor=%23555555&amp;style=plastic" alt="Bilangan pelawat laman"></a>';
const rows=[['JC-2026-0142','Jalan Pedas–Linggi','Jalan berlubang','Menunggu semakan','orange'],['JC-2026-0139','Jalan Chengkau','Turap semula','Menunggu kelulusan','amber'],['JC-2026-0134','Jalan Kota','Bahu jalan rosak','Sedang dilaksana','orange'],['JC-2026-0128','Jalan Astana Raja','Retakan permukaan','Selesai','green'],['JC-2026-0125','Jalan Sepri','Jalan berlubang','Lewat','red']];
const pageCategories={dashboard:'Utama','permohonan-baru':'Permohonan','permohonan-senarai':'Permohonan',semakan:'Semakan & Penilaian',kelulusan:'Semakan & Kelulusan',pelaksanaan:'Pelaksanaan',pengesahan:'Pengesahan',laporan:'Analisis & Laporan','pengguna-senarai':'Pentadbiran','pengguna-baharu':'Pentadbiran',panduan:'Bantuan',profil:'Akaun Pengguna'};
document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="sidebar-head"><div class="mini-logo">JKR</div><div class="brand-copy"><b>JalanCare</b><span>JKR Daerah Rembau</span></div><button class="sidebar-toggle" title="Kecilkan menu">☰</button></div><nav class="nav">${nav}</nav><div class="sidebar-user"><div class="avatar">${session?.name?.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="user-copy"><b>${session?.name}</b><span>${session?.role}</span></div></div></aside><div class="overlay"></div><div class="main"><header class="topbar"><button class="mobile-menu">☰</button><div class="topbar-title"><b>${pages[page]?.[0]}</b><span>${new Intl.DateTimeFormat('ms-MY',{dateStyle:'full'}).format(new Date())}</span></div><div class="top-actions"><button class="icon-button" title="Notifikasi">♢</button><button class="secondary logout">Log Keluar</button></div></header><main class="content">${content(page)}</main><footer class="site-footer"><div class="footer-copy"><b>JalanCare JKR Rembau</b><span>Prototaip Sistem Pengurusan Penyelenggaraan Jalan</span></div>${badge}</footer></div></div>`;
document.querySelector('.topbar-title b').textContent=pageCategories[page]||'JalanCare';
function heading(action=''){return `<div class="page-head"><div><span class="eyebrow">JalanCare</span><h1>${pages[page][0]}</h1><p>${pages[page][1]}</p></div>${action}</div>`}
function table(data=rows){return `<div class="table-wrap"><table><thead><tr><th>No. Rujukan</th><th>Lokasi</th><th>Kategori</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${data.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${r[4]}">${r[3]}</span></td><td><button class="text-button action-view">Lihat</button></td></tr>`).join('')}</tbody></table></div>`}
function dashboard(){const configs={Pemohon:{title:'Papan Pemuka Saya',desc:'Status permohonan yang anda hantar',action:`<a class="primary" href="${root}permohonan/baru.html">+ Permohonan Baharu</a>`,stats:[['6','Permohonan saya'],['2','Dalam semakan'],['1','Sedang dilaksanakan'],['3','Selesai']]},Juruteknik:{title:'Papan Pemuka Teknikal',desc:'Tugasan pemeriksaan dan semakan teknikal',stats:[['12','Menunggu pemeriksaan'],['4','Lawatan hari ini'],['3','Anggaran belum lengkap'],['18','Selesai bulan ini']]},'Jurutera Daerah':{title:'Papan Pemuka Kelulusan',desc:'Keputusan, kos dan kemajuan penyelenggaraan',stats:[['8','Menunggu kelulusan'],['RM 184k','Anggaran kos'],['5','Kerja lewat'],['27','Selesai bulan ini']]},'Pegawai Pelaksana':{title:'Papan Pemuka Pelaksanaan',desc:'Arahan kerja dan kemajuan di lapangan',stats:[['9','Kerja ditugaskan'],['4','Dijadualkan hari ini'],['3','Sedang dilaksanakan'],['2','Lewat']]},'Pegawai Pengesah':{title:'Papan Pemuka Pengesahan',desc:'Pemeriksaan hasil kerja dan penutupan rekod',stats:[['7','Menunggu pemeriksaan'],['3','Pemeriksaan hari ini'],['2','Pembaikan semula'],['21','Disahkan bulan ini']]},Pemerhati:{title:'Papan Pemuka Pengurusan',desc:'Prestasi keseluruhan tanpa akses pindaan',stats:[['48','Jumlah permohonan'],['92%','Dalam tempoh sasaran'],['9','Kerja aktif'],['27','Selesai bulan ini']]},Pentadbir:{title:'Papan Pemuka Sistem',desc:'Operasi, pengguna dan kesihatan sistem',action:`<a class="primary" href="${root}pengguna/baharu.html">+ Cipta Pengguna</a>`,stats:[['48','Jumlah permohonan'],['7','Pengguna aktif'],['12','Menunggu tindakan'],['27','Selesai bulan ini']]}};const c=configs[role]||configs.Pemohon;pages.dashboard=[c.title,c.desc];const statHtml=c.stats.map((s,i)=>`<div class="stat" style="--tone:${['#eaf4fa','#fff4dc','#fff0e5','#e8f7ef'][i]}"><div class="stat-icon">${['▤','⌛','⚒','✓'][i]}</div><strong>${s[0]}</strong><small>${s[1]}</small></div>`).join('');return heading(c.action||'')+`<section class="stats">${statHtml}</section><div class="grid-2"><section class="card"><div class="card-head"><h2>${role==='Pemohon'?'Permohonan terkini':'Tindakan mengikut peranan'}</h2><a class="text-button" href="${root}permohonan/senarai.html">Lihat semua</a></div>${table(rows.slice(0,4))}</section><section class="card"><div class="card-head"><h2>Ringkasan akses</h2></div><div class="card-body"><p class="muted">Anda log masuk sebagai <b>${role}</b>. Menu dan rekod dipaparkan mengikut tanggungjawab peranan ini.</p><ul class="activity"><li><i></i><div><b>${allowed.length} modul dibenarkan</b><span>Akses lain disekat secara automatik</span></div></li><li><i style="background:#15865d"></i><div><b>Sesi pengguna aktif</b><span>${session.name}</span></div></li></ul></div></section></div>`}
function content(p){if(p==='dashboard')return dashboard();
if(p==='permohonan-baru')return heading()+formApplication();if(p==='pengguna-baharu')return heading()+formUser();if(p==='profil')return heading()+profile();if(p==='panduan')return heading()+guide();if(p==='laporan')return heading(`<button class="primary action-demo">Eksport Laporan</button>`)+report();if(p==='pengguna-senarai')return heading(`<a class="primary" href="${root}pengguna/baharu.html">+ Cipta Pengguna</a>`)+users();
const labels={semakan:'Menunggu semakan teknikal',kelulusan:'Menunggu keputusan',pelaksanaan:'Kerja aktif',pengesahan:'Menunggu pengesahan','permohonan-senarai':role==='Pemohon'?'Permohonan saya':role==='Pegawai Pelaksana'?'Kerja ditugaskan':role==='Pegawai Pengesah'?'Menunggu pemeriksaan':'Semua rekod'};const scopedRows=role==='Pemohon'?rows.slice(0,2):role==='Pegawai Pelaksana'?rows.slice(2,4):role==='Pegawai Pengesah'?rows.filter(r=>r[3]==='Selesai'||r[3]==='Sedang dilaksana'):rows;return heading()+`<section class="card"><div class="filters"><input id="search" placeholder="Cari no. rujukan atau lokasi"><select id="statusFilter"><option value="">Semua status</option><option>Menunggu semakan</option><option>Menunggu kelulusan</option><option>Sedang dilaksana</option><option>Selesai</option></select></div><div class="card-head"><h2>${labels[p]||'Senarai kerja'}</h2><span class="muted">${scopedRows.length} rekod</span></div><div id="records">${table(scopedRows)}</div></section>`}
function formApplication(){return `<section class="card"><div class="card-head"><h2>Maklumat kerosakan</h2><span class="status orange">Draf baharu</span></div><form class="card-body demo-form"><div class="form-grid"><div class="field"><label>Nama pemohon</label><input required value="${session.name}"></div><div class="field"><label>No. telefon</label><input required placeholder="01X-XXXXXXX"></div><div class="field full"><label>Lokasi / nama jalan</label><input required placeholder="Contoh: Jalan Pedas–Linggi, KM 4.2"></div><div class="field"><label>Kategori kerosakan</label><select required><option value="">Pilih kategori</option><option>Jalan berlubang</option><option>Retakan permukaan</option><option>Bahu jalan rosak</option><option>Turap semula</option></select></div><div class="field"><label>Keutamaan</label><select><option>Biasa</option><option>Tinggi</option><option>Kecemasan</option></select></div><div class="field full"><label>Keterangan</label><textarea required placeholder="Terangkan keadaan kerosakan dan risiko kepada pengguna jalan."></textarea></div><div class="field"><label>Koordinat GPS</label><input placeholder="2.5900, 102.0900"></div><div class="field"><label>Gambar kerosakan</label><input type="file" accept="image/*"></div></div><div class="form-actions"><button type="button" class="secondary action-demo">Simpan Draf</button><button class="primary">Hantar Permohonan</button></div></form></section>`}
function formUser(){return `<section class="card"><div class="card-head"><h2>Maklumat akaun</h2><span class="status green">Pentadbir sahaja</span></div><form id="userForm" class="card-body"><div class="form-grid"><div class="field"><label>Nama penuh</label><input name="name" required></div><div class="field"><label>Nombor pekerja</label><input name="employee" required></div><div class="field"><label>E-mel rasmi</label><input name="email" type="email" required></div><div class="field"><label>Nombor telefon</label><input name="phone"></div><div class="field"><label>Jawatan</label><input name="position"></div><div class="field"><label>Bahagian / unit</label><input name="unit"></div><div class="field"><label>ID pengguna</label><input name="username" required></div><div class="field"><label>Peranan</label><select name="role"><option>Pemohon</option><option>Juruteknik</option><option>Jurutera Daerah</option><option>Pegawai Pelaksana</option><option>Pegawai Pengesah</option><option>Pemerhati</option><option>Pentadbir</option></select></div><div class="field"><label>Kata laluan sementara</label><input name="password" type="password" required></div><div class="field"><label>Status akaun</label><select name="status"><option>Aktif</option><option>Tidak Aktif</option></select></div><div class="field full"><label class="check"><input name="mustChange" type="checkbox" checked> Pengguna mesti menukar kata laluan selepas log masuk pertama</label></div></div><div class="form-actions"><a class="secondary" href="senarai.html">Batal</a><button class="primary">Cipta Pengguna</button></div></form></section>`}
function users(){const custom=JSON.parse(localStorage.getItem('jalancareUsers')||'[]'),base=[{name:'Nur Aina Ahmad',employee:'JKR1024',role:'Pentadbir',status:'Aktif'},{name:'Mohd Faris',employee:'JKR1187',role:'Juruteknik',status:'Aktif'},{name:'Ir. Siti Hajar',employee:'JKR0982',role:'Jurutera Daerah',status:'Aktif'}];return `<section class="card"><div class="filters"><input placeholder="Cari nama atau nombor pekerja"><select><option>Semua peranan</option><option>Pentadbir</option><option>Juruteknik</option><option>Jurutera Daerah</option></select></div><div class="table-wrap"><table><thead><tr><th>Pengguna</th><th>No. pekerja</th><th>Peranan</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${[...base,...custom].map(u=>`<tr><td><b>${u.name}</b></td><td>${u.employee}</td><td>${u.role}</td><td><span class="status green">${u.status}</span></td><td><button class="text-button action-demo">Edit</button></td></tr>`).join('')}</tbody></table></div></section>`}
function report(){if(role==='Juruteknik')return `<section class="stats"><div class="stat"><strong>12</strong><small>Menunggu pemeriksaan</small></div><div class="stat"><strong>4</strong><small>Lawatan hari ini</small></div><div class="stat"><strong>2.1 hari</strong><small>Purata masa semakan</small></div><div class="stat"><strong>14</strong><small>Lokasi berulang</small></div></section><section class="card"><div class="card-head"><h2>Jenis kerosakan diperiksa</h2></div><div class="card-body progress-list"><div class="progress-item"><div class="progress-top"><b>Jalan berlubang</b><span>72%</span></div><div class="bar"><span style="width:72%"></span></div></div><div class="progress-item"><div class="progress-top"><b>Retakan permukaan</b><span>48%</span></div><div class="bar"><span style="width:48%"></span></div></div><div class="progress-item"><div class="progress-top"><b>Bahu jalan</b><span>36%</span></div><div class="bar"><span style="width:36%"></span></div></div></div></section>`;return `<section class="stats"><div class="stat"><strong>5.8 hari</strong><small>Purata masa selesai</small></div><div class="stat"><strong>92%</strong><small>Dalam tempoh sasaran</small></div><div class="stat"><strong>RM 184k</strong><small>Anggaran kos bulan ini</small></div><div class="stat"><strong>14</strong><small>Lokasi kerosakan berulang</small></div></section><div class="grid-2"><section class="card"><div class="card-head"><h2>Kemajuan mengikut kategori</h2></div><div class="card-body progress-list"><div class="progress-item"><div class="progress-top"><b>Tambak / tampal</b><span>72%</span></div><div class="bar"><span style="width:72%"></span></div></div><div class="progress-item"><div class="progress-top"><b>Turap semula</b><span>48%</span></div><div class="bar"><span style="width:48%"></span></div></div><div class="progress-item"><div class="progress-top"><b>Bahu jalan</b><span>64%</span></div><div class="bar"><span style="width:64%"></span></div></div></div></section><section class="card"><div class="card-head"><h2>Prestasi bulanan</h2></div><div class="card-body"><p class="muted">27 daripada 31 kerja telah disiapkan dalam tempoh sasaran bulan ini.</p><div style="font-size:4rem;font-weight:800;color:var(--green)">87%</div></div></section></div>`}
function guide(){return `<section class="card"><div class="card-body guide-steps">${[['1','Daftar permohonan','Masukkan lokasi, kategori, keutamaan dan bukti bergambar.'],['2','Semakan teknikal','Juruteknik menilai kerosakan serta mencadangkan kaedah kerja.'],['3','Kelulusan','Jurutera menyemak skop, kuantiti dan anggaran kos.'],['4','Pelaksanaan','Pasukan kerja mengemas kini jadual, bahan dan kemajuan.'],['5','Pengesahan siap','Pegawai memeriksa hasil kerja dan bukti selepas pembaikan.'],['6','Laporan','Pengurusan memantau prestasi, kos, kelewatan dan trend.']].map(x=>`<div class="guide-step"><div class="step-no">${x[0]}</div><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div></section>`}
function profile(){return `<section class="card"><div class="card-body"><div style="display:flex;gap:18px;align-items:center;margin-bottom:24px"><div class="avatar" style="width:68px;height:68px;font-size:1.3rem">${session.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2 style="margin:0">${session.name}</h2><span class="status orange">${session.role}</span></div></div><div class="form-grid"><div class="field"><label>ID pengguna</label><input value="${session.username}" readonly></div><div class="field"><label>E-mel rasmi</label><input value="${session.username}@jkr.gov.my"></div><div class="field"><label>Nombor telefon</label><input placeholder="Belum ditetapkan"></div><div class="field"><label>Unit</label><input value="Bahagian Jalan"></div></div><div class="form-actions"><button class="primary action-demo">Simpan Perubahan</button></div></div></section>`}
const layout=document.querySelector('.layout');if(localStorage.getItem('jalancareCollapsed')==='1')layout.classList.add('collapsed');document.querySelector('.sidebar-toggle').onclick=()=>{layout.classList.toggle('collapsed');localStorage.setItem('jalancareCollapsed',layout.classList.contains('collapsed')?'1':'0')};document.querySelector('.mobile-menu').onclick=()=>layout.classList.add('menu-open');document.querySelector('.overlay').onclick=()=>layout.classList.remove('menu-open');document.querySelector('.logout').onclick=()=>{localStorage.removeItem('jalancareSession');sessionStorage.removeItem('jalancareSession');location.replace(root+'index.html')};
document.querySelectorAll('.demo-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();toast('Permohonan berjaya dihantar untuk semakan.')});document.querySelectorAll('.action-demo,.action-view').forEach(b=>b.onclick=()=>toast('Fungsi demonstrasi berjaya dilaksanakan.'));
const userForm=document.querySelector('#userForm');if(userForm)userForm.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(userForm));const list=JSON.parse(localStorage.getItem('jalancareUsers')||'[]');list.push({...data,status:data.status||'Aktif'});localStorage.setItem('jalancareUsers',JSON.stringify(list));toast('Pengguna baharu berjaya dicipta.');setTimeout(()=>location.href='senarai.html',700)};
const search=document.querySelector('#search');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('#records tbody tr').forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(q))};
function toast(msg){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2800)}
