const menu=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');if(menu){menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)})}
const siteHeader=document.querySelector('.site-header');if(siteHeader){const compactHeader=()=>siteHeader.classList.toggle('compact',scrollY>24);addEventListener('scroll',compactHeader,{passive:true});compactHeader()}
document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const target=document.getElementById(btn.dataset.copy);try{await navigator.clipboard.writeText(target.innerText);const old=btn.textContent;btn.textContent='✓ Berjaya disalin';setTimeout(()=>btn.textContent=old,1800)}catch(e){window.getSelection().selectAllChildren(target)}}));
const topBtn=document.querySelector('.back-top');if(topBtn){addEventListener('scroll',()=>topBtn.classList.toggle('show',scrollY>500));topBtn.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}))}
const checks=[...document.querySelectorAll('[data-complete]')];if(checks.length){checks.forEach(c=>{const key='kursus-'+c.dataset.complete;c.checked=localStorage.getItem(key)==='1';c.addEventListener('change',()=>{localStorage.setItem(key,c.checked?'1':'0');updateProgress()})});function updateProgress(){const done=checks.filter(c=>c.checked).length;const out=document.querySelector('[data-progress]');if(out)out.textContent=`${done} daripada ${checks.length} latihan selesai`;}updateProgress()}else{document.querySelectorAll('[data-progress]').forEach(e=>e.hidden=true)}
document.querySelectorAll('.footer').forEach(footer=>{footer.innerHTML='<div class="container"><div class="footer-grid"><div><h3>Kursus Alat Digital dan Analisis Penyelidikan</h3><p>Daripada carian literatur kepada analisis, visualisasi dan pelaporan.</p></div><div><h4>Navigasi Kursus</h4><a href="index.html">Utama</a><a href="tentatif.html">Tentatif</a><a href="modul/index.html">Modul</a><a href="latihan/index.html">Latihan</a></div><div><h4>Bahan &amp; Sumber</h4><a href="alatan/index.html">Alatan Penyelidikan</a><a href="ai-prompt.html">Prompt AI</a><a href="dataset.html">Hub Dataset</a><a href="alatan/modul-2/scopus-ai-prompts.html">Prompt Scopus AI</a><a href="alatan/index.html#muat-turun">Muat Turun Bahan</a></div></div><div class="footer-bottom"><p>© <span data-year></span> Universiti Teknologi Malaysia.<br>Penceramah: Prof. Madya Ts. Dr. Mohd Shahizan bin Othman.</p></div></div>';});
document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
document.querySelectorAll('.footer-bottom').forEach(footer=>{if(footer.querySelector('.visitor-badge'))return;const badge=document.createElement('a');badge.className='visitor-badge';badge.href='https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2Fdrshahizan';badge.target='_blank';badge.rel='noopener noreferrer';badge.innerHTML='<img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2Fdrshahizan&amp;labelColor=%23697689&amp;countColor=%23555555&amp;style=plastic" alt="Bilangan pelawat laman">';footer.appendChild(badge)});
if(!location.pathname.endsWith('/modul/modul-2-literatur-rujukan.html')&&!location.pathname.endsWith('/modul/modul-5-analisis-kualitatif.html')&&!location.pathname.endsWith('/modul/modul-6-visualisasi-penyelidikan.html')){const enhancementScript=document.createElement('script');enhancementScript.src='js/enhancements.js';document.body.appendChild(enhancementScript);}
const toolGuideScript=document.createElement('script');toolGuideScript.src='js/tool-guides.js';document.body.appendChild(toolGuideScript);
const guideNavScript=document.createElement('script');guideNavScript.src='js/guide-nav.js';document.body.appendChild(guideNavScript);
const onboardingScript=document.createElement('script');onboardingScript.src='js/onboarding.js';document.body.appendChild(onboardingScript);
const selfCheckScript=document.createElement('script');selfCheckScript.src='js/self-check.js';document.body.appendChild(selfCheckScript);
const navigationScript=document.createElement('script');navigationScript.src='js/navigation.js';document.body.appendChild(navigationScript);
if(location.pathname.endsWith('/alatan/modul-2/publish-or-perish/antara-muka.html')){const grid=document.querySelector('main section .grid');if(grid)grid.insertAdjacentHTML('beforebegin','<figure class="interface-image"><img src="assets/images/publish-or-perish-interface.png" alt="Paparan Publish or Perish dengan panel navigasi, pertanyaan, statistik dan senarai penerbitan"><figcaption>Bahagian utama antara muka Publish or Perish.</figcaption></figure>');}
document.querySelectorAll('a[href^="latihan/index.html#latihan-"]').forEach(a=>{const n=a.getAttribute('href').match(/latihan-(\d+)/)?.[1];if(n)a.href=`latihan/latihan-modul-${n}.html`;});
if(location.pathname.endsWith('/alatan/index.html')){const h=[...document.querySelectorAll('h2')].find(x=>x.textContent.includes('Alat digital berasaskan AI'));const c=h?.closest('section')?.querySelector('.container');if(c&&!c.querySelector('[href="alatan/modul-7/gemini-notebook/index.html"]'))c.querySelector('.grid')?.insertAdjacentHTML('beforebegin','<div class="tools-grid" style="margin-bottom:24px"><a class="tool-card" href="alatan/modul-7/gemini-notebook/index.html"><strong>Gemini Notebook →</strong><small>Panduan sumber, chat bersitasi, Studio, etika dan latihan hands-on.</small><span class="type">● Hands-on utama · Akaun Google</span></a><a class="tool-card" href="alatan/modul-7/alat-ai-penyelidikan.html"><strong>AI untuk Penyelidikan →</strong><small>Prinsip prompt, semakan manusia dan penggunaan AI secara beretika.</small><span class="type">● Panduan utama</span></a></div>');}
if(location.pathname.endsWith('/modul/modul-7-ai-penyelidikan.html'))setTimeout(()=>{const g=document.querySelector('.tools-grid');if(g&&!g.querySelector('[href="alatan/modul-7/gemini-notebook/index.html"]'))g.insertAdjacentHTML('afterbegin','<a class="tool-card" href="alatan/modul-7/gemini-notebook/index.html"><strong>Gemini Notebook →</strong><small>Sintesis dan output berasaskan sumber.</small><span class="type">Panduan alat</span></a>');},100);
document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('a[href="https://notebook.google.com/"]').forEach(a=>a.href='https://notebooklm.google.com/');
  const toolVisuals={'Publish or Perish':'assets/images/tools/publish-or-perish.svg','Scopus AI':'assets/images/tools/scopus-ai.svg','Gemini Notebook':'assets/images/tools/notebooklm.svg'};
  document.querySelectorAll('.tool-card').forEach(card=>{const strong=card.querySelector('strong');if(!strong)return;const name=strong.textContent.replace('→','').trim();const src=toolVisuals[name];if(src&&!card.querySelector('img')){const img=document.createElement('img');img.src=src;img.alt=`Visual ringkas ${name}`;img.loading='lazy';img.width=1200;img.height=675;card.prepend(img);}});
  const guide=document.querySelector('#learning-guide');if(guide){const key=document.body.dataset.guide||'';const visual=key.startsWith('scopus-ai')?['assets/images/tools/scopus-ai.svg','Aliran kerja Scopus AI: pertanyaan, ringkasan, rujukan dan artikel asal']:key.startsWith('gemini-notebook')?['assets/images/tools/notebooklm.svg','Aliran kerja Gemini Notebook: Sources, Chat, semakan dan Studio']:null;if(visual){const section=guide.querySelector('section .container');const figure=document.createElement('figure');figure.className='guide-visual';figure.innerHTML=`<img src="${visual[0]}" alt="${visual[1]}" width="1200" height="675"><figcaption><strong>Gambaran proses:</strong> ${visual[1]}.</figcaption>`;section?.prepend(figure);}}
  const path=location.pathname;
  const addVisual=(src,alt,caption)=>{const target=document.querySelector('main section .container');if(!target||target.querySelector('.guide-visual'))return;const f=document.createElement('figure');f.className='guide-visual';f.innerHTML=`<img src="${src}" alt="${alt}" width="1200" height="675"><figcaption><strong>Gambaran proses:</strong> ${caption}</figcaption>`;target.prepend(f);};
  if(path.endsWith('/scopus-ai/index.html'))addVisual('assets/images/tools/scopus-ai.svg','Aliran kerja Scopus AI','Gunakan Scopus AI untuk penerokaan, kemudian semak dan cite artikel asal.');
  if(path.endsWith('/gemini-notebook/index.html')){addVisual('assets/images/tools/notebooklm.svg','Aliran kerja Gemini Notebook','Tambah sumber, bertanya dengan sitasi, semak bukti dan hasilkan output.');document.title='Panduan Gemini Notebook';}
  if(path.endsWith('/publish-or-perish/antara-muka.html'))addVisual('assets/images/publish-or-perish-interface.png','Paparan antara muka Publish or Perish yang menunjukkan panel carian, statistik dan senarai hasil','Kenal pasti panel carian, statistik dan senarai rekod sebelum latihan.');
});
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
  const replacements=[['Literatur, Rujukan & Sitasi','Pengurusan Literatur & Analisis Rujukan'],['Literatur & Rujukan','Pengurusan Literatur & Analisis Rujukan'],['Literatur & Sitasi','Pengurusan Literatur & Analisis Rujukan']];
  const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))for(const [a,b] of replacements)if(n.textContent.includes(a))n.textContent=n.textContent.replaceAll(a,b);
  document.querySelectorAll('a[href*="alat-microsoft-academic.html"]').forEach(a=>a.remove());
  const path=location.pathname;
  if(path.endsWith('/alatan/modul-2.html')||path.endsWith('/modul/modul-2-literatur-rujukan.html')){
    const grid=document.querySelector('.tools-grid');
    if(grid&&!grid.querySelector('a[href="alatan/modul-3/scopus-ai/index.html"]'))grid.insertAdjacentHTML('afterbegin','<a class="tool-card" href="alatan/modul-3/scopus-ai/index.html"><img src="assets/images/tools/scopus-ai.svg" alt="Visual ringkas Scopus AI" loading="lazy" width="1200" height="675"><strong>Scopus AI →</strong><small>Penerokaan topik, istilah, karya asas dan rujukan.</small><span class="type">Panduan alat</span></a>');
  }
},250));
document.addEventListener('DOMContentLoaded',()=>{
  const path=location.pathname;
  if(path.endsWith('/latihan/modul-5/latihan-5.html')){
    const next=document.querySelector('.module-nav .next');
    if(next){next.href='latihan/modul-5/latihan-6.html';next.textContent='Latihan 6 →';}
  }
  const brand=document.querySelector('.brand');
  if(brand&&!brand.querySelector('.brand-mark'))brand.insertAdjacentHTML('afterbegin','<span class="brand-mark">AD</span>');
});
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode()))if(node.textContent.includes('Looker Studio'))node.textContent=node.textContent.replaceAll('Looker Studio','Google Data Studio');
  document.querySelectorAll('a[href="alatan/modul-6/alat-looker-studio.html"]').forEach(a=>a.href='alatan/modul-6/alat-google-data-studio.html');
},300));
