const menu=document.querySelector('.menu-btn'),links=document.querySelector('.links');menu?.addEventListener('click',()=>{links.classList.toggle('open');menu.setAttribute('aria-expanded',links.classList.contains('open'))});document.querySelectorAll('.dropbtn').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.parentElement.classList.toggle('open')}));document.addEventListener('click',()=>document.querySelectorAll('.dropdown').forEach(d=>d.classList.remove('open')));
document.querySelectorAll('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const text=btn.closest('.prompt-box,.prompt-card').querySelector('.prompt-text').innerText;await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='✓ Disalin';setTimeout(()=>btn.textContent=old,1800)}));
const q=document.querySelector('#promptSearch'),f=document.querySelector('#promptFilter');function filterPrompts(){const term=(q?.value||'').toLowerCase(),cat=f?.value||'all';let n=0;document.querySelectorAll('.prompt-card').forEach(c=>{const show=c.innerText.toLowerCase().includes(term)&&(cat==='all'||c.dataset.category===cat);c.style.display=show?'block':'none';if(show)n++});const empty=document.querySelector('.empty');if(empty)empty.style.display=n?'none':'block'}q?.addEventListener('input',filterPrompts);f?.addEventListener('change',filterPrompts);
document.querySelectorAll('a[href="https://drshahizan.github.io/fk/latihan-gemini-notebook-sspa.html"]').forEach(a=>{a.href='latihan-gemini-notebook-skim-pendidikan.html';a.removeAttribute('target');a.removeAttribute('rel');a.textContent=a.textContent.replace('↗','→')});
const attendance=document.querySelector('#latihan51');if(attendance&&!attendance.querySelector('.dataset-download')){const box=document.createElement('div');box.className='actions dataset-download';box.innerHTML='<a class="btn btn-gold" href="assets/documents/dataset-kehadiran-kelas-5-bestari.xlsx" download>Muat Turun Dataset XLSX ↓</a><a class="btn btn-secondary" href="latihan-analisis-kehadiran.html">Buka Panduan Langkah demi Langkah →</a>';attendance.appendChild(box)}
const current=location.pathname.split('/').pop();
const lesson=document.querySelector('.lesson');
if(lesson&&['sesi-4.html','sesi-5.html'].includes(current)){
  const extra=document.createElement('section');
  extra.className='prompt-box';
  if(current==='sesi-4.html')extra.innerHTML='<h2>Sumber tambahan berkaitan</h2><p>Teruskan penerokaan selepas sesi ini melalui koleksi kendiri berikut.</p><div class="resource-links"><a href="latihan-penyediaan-slaid.html">Latihan penyediaan slaid →</a><a href="latihan-multimedia-sekolah.html">Latihan multimedia sekolah →</a><a href="standard-grafik.html">Standard grafik sekolah →</a><a href="prompt-visual.html">Prompt visual sekolah →</a></div>';
  else extra.innerHTML='<h2>Sumber tambahan berkaitan</h2><p>Gunakan koleksi berikut untuk aplikasi AI yang lebih luas dalam pengurusan sekolah.</p><div class="resource-links"><a href="latihan-dokumen-pentadbiran.html">Latihan dokumen pentadbiran →</a><a href="latihan-pengacara-majlis.html">Latihan pengacara majlis →</a><a href="prompt-pentadbiran.html">Prompt pentadbiran sekolah →</a><a href="prompt-visual.html">Prompt visual sekolah →</a></div>';
  lesson.appendChild(extra);
}
