const $=(selector,context=document)=>context.querySelector(selector),$$=(selector,context=document)=>[...context.querySelectorAll(selector)];
if(localStorage.theme==='dark')document.body.classList.add('dark');
$('#promptTheme')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'});
const escapeHTML=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
let promptCategory='all';
function renderFilters(){const holder=$('#promptFilters');holder.innerHTML=`<button class="active" data-category="all">Semua</button>${window.PROMPT_CATEGORIES.map(c=>`<button data-category="${c.id}">${c.icon} ${c.name}</button>`).join('')}`;$$('[data-category]',holder).forEach(button=>button.addEventListener('click',()=>{promptCategory=button.dataset.category;$$('[data-category]',holder).forEach(item=>item.classList.toggle('active',item===button));renderPrompts($('#promptSearch').value)}))}
function renderPrompts(query=''){const q=query.trim().toLowerCase(),cards=[];window.PROMPT_CATEGORIES.forEach(category=>category.prompts.forEach(prompt=>{if((promptCategory==='all'||promptCategory===category.id)&&(!q||`${prompt.title} ${prompt.text} ${category.name}`.toLowerCase().includes(q)))cards.push({category,prompt})}));$('#promptGrid').innerHTML=cards.map(({category,prompt})=>`<details class="prompt-card"><summary><span class="prompt-number">${String(prompt.n).padStart(2,'0')}</span><span><small>${category.icon} ${category.name}</small><b>${escapeHTML(prompt.title)}</b></span><i>+</i></summary><div class="prompt-body"><pre>${escapeHTML(prompt.text)}</pre><button class="prompt-copy" data-number="${prompt.n}">Salin Prompt</button></div></details>`).join('')||'<p class="prompt-empty">Tiada prompt ditemui. Cuba kata kunci lain.</p>';$$('.prompt-copy').forEach(button=>button.addEventListener('click',async()=>{const item=window.PROMPT_CATEGORIES.flatMap(category=>category.prompts).find(prompt=>prompt.n===Number(button.dataset.number));await navigator.clipboard.writeText(item.text);button.textContent='Telah disalin ✓';setTimeout(()=>button.textContent='Salin Prompt',1600)}))}
renderFilters();renderPrompts();$('#promptSearch').addEventListener('input',event=>renderPrompts(event.target.value));
$$('.guide-copy[data-copy]').forEach(button=>button.addEventListener('click',async()=>{await navigator.clipboard.writeText(button.dataset.copy);button.textContent='Telah disalin ✓';setTimeout(()=>button.textContent='Salin Struktur',1500)}));
$('#buildPrompt').addEventListener('click',()=>{const role=$('#labRole').value.trim(),task=$('#labTask').value.trim(),context=$('#labContext').value.trim(),format=$('#labFormat').value.trim(),constraint=$('#labConstraint').value.trim();if(!task){$('#labOutput').textContent='Masukkan tugasan yang ingin dihasilkan.';return}$('#labOutput').textContent=`Bertindak sebagai ${role||'setiausaha profesional di UTM'}. ${task}. Berdasarkan konteks berikut: ${context||'[masukkan konteks]'}. Susun jawapan dalam format ${format||'[nyatakan format]'}. Patuhi kekangan berikut: ${constraint||'gunakan bahasa profesional dan jangan mereka maklumat'}.`;$('#copyLab').hidden=false});
$('#copyLab').addEventListener('click',async event=>{await navigator.clipboard.writeText($('#labOutput').textContent);event.currentTarget.textContent='Telah disalin ✓';setTimeout(()=>event.currentTarget.textContent='Salin Prompt',1500)});
const topButton=$('#guideTop');addEventListener('scroll',()=>topButton.classList.toggle('show',scrollY>600),{passive:true});topButton.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
