/* UBAH URL DI BAWAH SAHAJA selepas deploy Google Apps Script. */
window.JALANCARE_CONFIG={API_URL:"MASUKKAN_URL_GOOGLE_APPS_SCRIPT_WEB_APP",APP_NAME:"JalanCare",API_VERSION:"2.0",REQUEST_TIMEOUT_MS:20000};
