const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const slideTopics=['Tajuk Program','Setiausaha UTM','Selamat Datang','Objektif Program','Perjalanan Pembelajaran','Cabaran Setiausaha','Apakah AI','Teknologi Masa Depan','Landskap AI','ELIZA','Pekerjaan dan Automasi','Teknologi dan Kerja','Manusia dan AI','AI Generatif vs AI Beragen','Statistik Penggunaan AI','Kegunaan AI Generatif','NotebookLM UTM','Kenal Pasti Imej AI','Etika dan Risiko','Evolusi Visual AI','Gemini dan NotebookLM','Google Gemini','Gemini Nano Banana','Ciri Gemini','Gemini untuk Setiausaha','Prompt Gemini','Penghasilan Slaid','Penghasilan Laporan','Pelan Tindakan','Penghasilan Carta','Penghasilan Poster','Penghasilan Muzik','Lembaran Watak','Storyboard','Penghasilan Video','Audio kepada Minit','Contoh Poster','Contoh Poster','Contoh Poster','Contoh Poster','Gemini Notebook','Kebaikan Notebook','Studio Notebook','Audio Overview','Slide Deck','Video Overview','Peta Minda','Laporan','Kad Imbas','Infografik','Kuiz','Warisan UTM','Revolusi AI','UTM Equine Centre','UTM Library Vision','Data Sukan','Data Sukan','Infografik Sukan','Poster Sukan','Terima Kasih'];
const tools=[
 {name:'Google Gemini',cat:'writing visual',tag:'Pembantu serba boleh',desc:'Menghasilkan e-mel, laporan, jadual, imej, slaid dan analisis.',url:'https://gemini.google.com'},
 {name:'Gemini Notebook',cat:'research writing',tag:'Berasaskan sumber',desc:'Menukar koleksi dokumen kepada audio, laporan, peta minda, kuiz dan infografik.',url:'https://notebooklm.google.com'},
 {name:'ChatGPT',cat:'writing research',tag:'Idea & penulisan',desc:'Membangunkan idea, menyusun kandungan dan membantu analisis berasaskan arahan.',url:'https://chatgpt.com'},
 {name:'Napkin AI',cat:'visual',tag:'Visual pantas',desc:'Menukar teks kepada rajah dan visual komunikasi yang kemas.',url:'https://www.napkin.ai'},
 {name:'Canva',cat:'visual',tag:'Reka bentuk',desc:'Menghasilkan bahan komunikasi, poster, infografik dan pembentangan.',url:'https://www.canva.com'},
 {name:'Gamma',cat:'visual writing',tag:'Pembentangan',desc:'Membina pembentangan dan dokumen visual daripada rangka kandungan.',url:'https://gamma.app'},
 {name:'Claude',cat:'writing research',tag:'Dokumen panjang',desc:'Membantu membaca, menyusun dan memperhalus kandungan yang kompleks.',url:'https://claude.ai'},
 {name:'Perplexity',cat:'research',tag:'Carian bersumber',desc:'Mencari jawapan semasa dengan pautan kepada sumber rujukan.',url:'https://www.perplexity.ai'},
 {name:'Google AI Studio',cat:'writing visual',tag:'Eksperimen AI',desc:'Menguji model Gemini, prompt multimodal dan prototaip AI.',url:'https://aistudio.google.com'}];
const demos={
 gemini:{title:'Google Gemini',description:'Panduan penggunaan Gemini untuk komunikasi rasmi, mesyuarat, dokumen, slaid, laporan, carta, poster, muzik, video dan minit mesyuarat.',slides:Array.from({length:13},(_,i)=>i+24)},
 notebook:{title:'Gemini Notebook',description:'Panduan menukar sumber kepada audio, slaid, video, peta minda, laporan, kad imbas, infografik dan kuiz.',slides:Array.from({length:10},(_,i)=>i+41)}
};
function renderTools(filter='all'){const grid=$('#toolGrid');grid.innerHTML=tools.filter(t=>filter==='all'||t.cat.includes(filter)).map((t,i)=>`<article class="tool-card"><div class="logo">${t.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><small>${t.tag}</small><h3>${t.name}</h3><p>${t.desc}</p><a href="${t.url}" target="_blank" rel="noopener">Laman rasmi ↗</a></article>`).join('')}
function renderDemo(key='gemini'){const d=demos[key],first=d.slides[0];$('#tabContent').innerHTML=`<div class="tool-slides-intro"><div><p class="eyebrow">${d.slides.length} SLAID PANDUAN</p><h3>${d.title}</h3><p>${d.description}</p></div><span>Slaid ${d.slides[0]}–${d.slides.at(-1)}</span></div><button class="tool-slide-main" data-main-slide="${first}" aria-label="Buka Slaid ${first} dalam paparan penuh"><img src="assets/slides/slide-${String(first).padStart(2,'0')}.jpg" alt="${d.title}, Slaid ${first}"><small>Slaid ${first} · Klik untuk paparan penuh</small></button><div class="tool-slide-strip" aria-label="Senarai slaid ${d.title}">${d.slides.map((slide,index)=>`<button class="tool-slide-thumb${index===0?' active':''}" data-tool-slide="${slide}" aria-label="Paparkan Slaid ${slide}"><img loading="lazy" src="assets/slides/slide-${String(slide).padStart(2,'0')}.jpg" alt="Thumbnail Slaid ${slide}"><span>${slide}</span></button>`).join('')}</div>`;const main=$('.tool-slide-main');main.onclick=()=>openSlide(Number(main.dataset.mainSlide));$$('.tool-slide-thumb').forEach(button=>button.onclick=()=>{const slide=Number(button.dataset.toolSlide);$$('.tool-slide-thumb').forEach(x=>x.classList.toggle('active',x===button));main.dataset.mainSlide=slide;$('img',main).src=`assets/slides/slide-${String(slide).padStart(2,'0')}.jpg`;$('img',main).alt=`${d.title}, Slaid ${slide}`;$('small',main).textContent=`Slaid ${slide} · Klik untuk paparan penuh`})}
function renderGallery(query=''){const q=query.toLowerCase(),items=slideTopics.map((topic,i)=>({topic,i:i+1})).filter(x=>x.topic.toLowerCase().includes(q)||String(x.i).includes(q));$('#galleryGrid').innerHTML=items.map(x=>`<button class="gallery-item" data-slide="${x.i}" aria-label="Buka slaid ${x.i}: ${x.topic}"><img loading="lazy" src="assets/slides/slide-${String(x.i).padStart(2,'0')}.jpg" alt="Slaid ${x.i}: ${x.topic}"><span>${String(x.i).padStart(2,'0')} · ${x.topic}</span></button>`).join('');$('#galleryCount').textContent=`${items.length} visual`;$$('.gallery-item').forEach(b=>b.onclick=()=>openSlide(+b.dataset.slide))}
function escapeHTML(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
let promptCategory='all';
function renderPromptFilters(){const holder=$('#promptFilters');holder.innerHTML=`<button class="active" data-prompt-category="all">Semua</button>${window.PROMPT_CATEGORIES.map(c=>`<button data-prompt-category="${c.id}">${c.icon} ${c.name}</button>`).join('')}`;$$('[data-prompt-category]',holder).forEach(button=>button.onclick=()=>{promptCategory=button.dataset.promptCategory;$$('[data-prompt-category]',holder).forEach(x=>x.classList.toggle('active',x===button));renderPrompts($('#promptSearch').value)})}
function renderPrompts(query=''){const q=query.trim().toLowerCase();const cards=[];window.PROMPT_CATEGORIES.forEach(category=>category.prompts.forEach(prompt=>{if((promptCategory==='all'||promptCategory===category.id)&&(!q||`${prompt.title} ${prompt.text} ${category.name}`.toLowerCase().includes(q)))cards.push({category,prompt})}));$('#promptGrid').innerHTML=cards.map(({category,prompt})=>`<details class="prompt-card"><summary><span class="prompt-number">${String(prompt.n).padStart(2,'0')}</span><span><small>${category.icon} ${category.name}</small><b>${escapeHTML(prompt.title)}</b></span><i>+</i></summary><div class="prompt-body"><pre>${escapeHTML(prompt.text)}</pre><button class="prompt-copy" data-prompt-number="${prompt.n}">Salin Prompt</button></div></details>`).join('')||`<p class="prompt-empty">Tiada prompt ditemui. Cuba kata kunci lain.</p>`;$$('.prompt-copy').forEach(button=>button.onclick=async()=>{const item=window.PROMPT_CATEGORIES.flatMap(c=>c.prompts).find(p=>p.n===Number(button.dataset.promptNumber));await navigator.clipboard.writeText(item.text);button.textContent='Telah disalin ✓';setTimeout(()=>button.textContent='Salin Prompt',1800)})}
let currentSlide=1;function openSlide(n){currentSlide=(n+59)%60+1;const l=$('#lightbox');$('img',l).src=`assets/slides/slide-${String(currentSlide).padStart(2,'0')}.jpg`;$('img',l).alt=`Slaid ${currentSlide}: ${slideTopics[currentSlide-1]}`;$('p',l).textContent=`${currentSlide} / 60 · ${slideTopics[currentSlide-1]}`;l.classList.add('open')}
function charts(){if(!window.Chart)return;Chart.defaults.font.family="'DM Sans', Arial, sans-serif";Chart.defaults.color='#6d6265';const base={responsive:true,maintainAspectRatio:false,resizeDelay:120,animation:{duration:700},plugins:{tooltip:{enabled:true,backgroundColor:'#4c0012',padding:12}}};new Chart($('#usageChart'),{type:'bar',data:{labels:['18–24','25–34','35–44','45–54','55–65'],datasets:[{label:'Wanita',data:[59,60,51,42,34],backgroundColor:'#7a0019',borderRadius:8},{label:'Lelaki',data:[71,70,61,49,42],backgroundColor:'#d6a84b',borderRadius:8}]},options:{...base,plugins:{...base.plugins,legend:{position:'bottom'}},scales:{y:{beginAtZero:true,max:80,ticks:{callback:value=>`${value}%`},grid:{color:'rgba(130,100,108,.12)'}},x:{grid:{display:false}}}}});new Chart($('#purposeChart'),{type:'bar',data:{labels:['Mencari maklumat','Menjana idea','Menghasilkan teks','Ringkasan','Terjemahan','Imej'],datasets:[{label:'Responden (%)',data:[66,49,43,35,30,27],backgroundColor:['#7a0019','#8d1831','#a53a50','#bb6574','#d6a84b','#e5c988'],borderRadius:8,barThickness:24}]},options:{...base,indexAxis:'y',plugins:{...base.plugins,legend:{display:false}},scales:{x:{beginAtZero:true,max:80,ticks:{callback:value=>`${value}%`},grid:{color:'rgba(130,100,108,.12)'}},y:{grid:{display:false}}}}})}
window.addEventListener('load',()=>{setTimeout(()=>{$('#loader').style.opacity=0;setTimeout(()=>$('#loader').remove(),600)},350);renderTools();renderDemo();renderGallery();charts();if(!localStorage.cookieOK)$('#cookie').style.display='flex';if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')});
window.addEventListener('scroll',()=>{const h=document.documentElement;$('#progress').style.width=`${h.scrollTop/(h.scrollHeight-h.clientHeight)*100}%`;$('#nav').classList.toggle('scrolled',scrollY>20);$('#backTop').classList.toggle('show',scrollY>700)});
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal,.section-head,.challenge-grid article,.objective-grid article,.timeline article').forEach(x=>{x.classList.add('reveal');observer.observe(x)});
$('.menu').onclick=()=>$('.nav nav').classList.toggle('open');$$('.nav nav a').forEach(a=>a.onclick=()=>$('.nav nav').classList.remove('open'));$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTools(b.dataset.filter)});$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDemo(b.dataset.tab)});
$('#gallerySearch').oninput=e=>renderGallery(e.target.value);$('#backTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#assistantBtn').onclick=()=>$('#assistant').classList.toggle('open');$('#assistant>button').onclick=()=>$('#assistant').classList.remove('open');$('#cookie button').onclick=()=>{localStorage.cookieOK='1';$('#cookie').remove()};
$('#searchBtn').onclick=()=>{$('#searchModal').classList.add('open');setTimeout(()=>$('#siteSearch').focus(),50)};$$('.modal .close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$('#siteSearch').oninput=e=>{const q=e.target.value.toLowerCase();const hits=[...document.querySelectorAll('section h2,section h3')].filter(x=>x.textContent.toLowerCase().includes(q)).slice(0,8);$('#searchResults').innerHTML=hits.map(x=>`<a class="result" href="#${x.closest('section').id}" onclick="document.querySelector('#searchModal').classList.remove('open')">${x.textContent}</a>`).join('')};
$('#lightbox .prev').onclick=()=>openSlide(currentSlide-1);$('#lightbox .next').onclick=()=>openSlide(currentSlide+1);document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal').forEach(x=>x.classList.remove('open'));if($('#lightbox').classList.contains('open')&&e.key==='ArrowLeft')openSlide(currentSlide-1);if($('#lightbox').classList.contains('open')&&e.key==='ArrowRight')openSlide(currentSlide+1)});$('#shareBtn').onclick=async()=>{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);$('#shareBtn').textContent='Pautan disalin ✓'}};
const sections=$$('main section[id]'),navLinks=$$('.nav nav a');new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-40% 0px -50%'}).observe(sections[0]);sections.slice(1).forEach(s=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-40% 0px -50%'}).observe(s));
