const trainingGuides={
'4.1':{steps:['Pilih mata pelajaran, tahun, topik dan tempoh PdP.','Salin standard pembelajaran daripada dokumen rasmi tanpa mengubah kod.','Jana RPH untuk tiga aras murid menggunakan prompt yang disediakan.','Semak penjajaran objektif, aktiviti dan pentaksiran.','Simpan RPH akhir selepas semakan guru.'],prompt:'Anda ialah pemimpin instruksional sekolah rendah. Berdasarkan standard pembelajaran yang saya berikan, bina RPH bagi [MATA PELAJARAN], Tahun [TAHUN], topik [TOPIK] selama [TEMPOH]. Sediakan aktiviti pemulihan, sederhana dan pengayaan. Sertakan objektif boleh diukur, bukti pembelajaran dan pentaksiran formatif. Jangan cipta kod kurikulum.',result:'RPH berbeza aras yang telah disemak.'},
'4.2':{steps:['Tetapkan topik, tahun dan objektif pembelajaran.','Minta Gemini membina tiga soalan berasaskan situasi sekolah atau komuniti Malaysia.','Semak aras kognitif dan kejelasan bahasa setiap soalan.','Jana skema jawapan dan jadual spesifikasi ringkas.','Uji soalan terhadap objektif sebelum menyimpannya.'],prompt:'Hasilkan tiga soalan KBAT bagi [TOPIK] untuk murid Tahun [TAHUN]. Gunakan konteks kehidupan sebenar di Malaysia. Bagi setiap soalan, nyatakan aras kognitif, objektif yang diuji, cadangan jawapan, markah dan justifikasi. Akhiri dengan jadual spesifikasi ringkas.',result:'Set soalan KBAT, skema dan jadual spesifikasi.'},
'4.3':{steps:['Pilih tugasan atau hasil kerja murid yang hendak dinilai.','Senaraikan tiga hingga lima kriteria yang boleh diperhatikan.','Jana deskriptor bagi empat tahap pencapaian.','Semak supaya setiap deskriptor jelas, berbeza dan boleh diukur.','Uji rubrik pada satu contoh kerja rekaan dan baiki kekaburan.'],prompt:'Bina rubrik analitik empat tahap untuk menilai [TUGASAN]. Gunakan kriteria [KRITERIA]. Setiap deskriptor mesti khusus, boleh diperhatikan dan tidak bertindih. Sertakan wajaran, kaedah pengiraan skor dan contoh ringkas bagi setiap tahap.',result:'Rubrik analitik yang boleh terus digunakan.'},
'4.4':{steps:['Muat turun dan buka dataset prestasi rekaan.','Semak lajur, nilai kosong dan konsistensi tahap penguasaan.','Minta Gemini mengenal pasti jurang penguasaan dan kelompok murid.','Bina intervensi empat minggu dengan KPI dan kaedah pemantauan.','Semak cadangan dengan guru mata pelajaran sebelum digunakan.'],prompt:'Analisis dataset prestasi kelas yang dimuat naik. Kenal pasti jurang penguasaan, kelompok murid yang memerlukan pemulihan dan pengayaan serta pola mengikut topik. Bina pelan intervensi empat minggu dalam jadual Minggu | Sasaran | Aktiviti | Pegawai | Bukti | KPI. Gunakan data yang diberikan sahaja.',result:'Analisis jurang dan pelan intervensi empat minggu.'},
'4.5':{steps:['Cipta notebook baharu mengikut mata pelajaran.','Muat naik DSKP, RPH dan instrumen pentaksiran yang berkaitan.','Pastikan semua sumber berjaya diproses.','Minta Gemini Notebook memetakan standard, objektif, aktiviti dan pentaksiran.','Semak setiap dapatan melalui rujukan sumber sebelum membaiki RPH.'],prompt:'Berdasarkan sumber notebook sahaja, semak keselarasan antara standard pembelajaran, objektif RPH, aktiviti, instrumen pentaksiran dan bukti pembelajaran. Hasilkan jadual Komponen | Bukti sumber | Status | Jurang | Cadangan pembetulan. Nyatakan halaman atau sumber bagi setiap dapatan.',result:'Laporan keselarasan RPH berasaskan sumber.'},
'4.6':{steps:['Muat naik DSKP, nota dan bahan pengajaran yang telah disahkan.','Tetapkan topik, tahun, jenis soalan dan jumlah soalan.','Jana soalan objektif, struktur dan KBAT secara berasingan.','Minta skema jawapan serta rujukan sumber bagi setiap soalan.','Semak fakta, aras bahasa, kesukaran dan liputan kandungan.'],prompt:'Gunakan sumber notebook sahaja untuk membina bank soalan bagi [TOPIK], Tahun [TAHUN]. Sediakan [BILANGAN] soalan objektif, struktur dan KBAT berserta jawapan, markah, aras kognitif dan rujukan sumber. Jangan bina soalan bagi kandungan yang tiada dalam sumber.',result:'Bank soalan dan skema yang dapat dikesan kepada sumber.'},
'4.7':{steps:['Susun sumber notebook mengikut topik pembelajaran.','Minta ringkasan konsep dan istilah penting.','Gunakan Studio untuk menghasilkan peta minda, slaid, audio, kuiz dan kad imbas.','Semak keseragaman fakta antara semua hasil Studio.','Eksport bahan yang sesuai dan rekodkan pembetulan guru.'],prompt:'Hasilkan kit pembelajaran bagi [TOPIK] untuk murid Tahun [TAHUN] menggunakan sumber notebook sahaja. Kandungan mesti menekankan konsep teras, contoh mudah, salah faham lazim dan aktiviti refleksi. Gunakan bahasa sesuai umur dan kekalkan fakta serta istilah yang sama dalam semua hasil Studio.',result:'Kit nota, peta minda, slaid, audio, kuiz dan kad imbas.'},
'4.8':{steps:['Muat naik dataset PBD rekaan atau data agregat yang dinyahidentiti.','Semak struktur, tempoh pentaksiran dan skala tahap penguasaan.','Bandingkan perkembangan mengikut kelas, topik atau tempoh.','Kenal pasti murid sasaran menggunakan kriteria yang dipersetujui.','Hasilkan ringkasan panitia dan pelan pemantauan.'],prompt:'Analisis data PBD yang dimuat naik. Semak kualiti data, bandingkan perkembangan tahap penguasaan mengikut tempoh, kenal pasti pola dan murid sasaran berdasarkan kriteria [KRITERIA]. Hasilkan ringkasan untuk mesyuarat panitia serta cadangan intervensi. Jangan membuat kesimpulan sebab-akibat.',result:'Analisis perkembangan, kumpulan sasaran dan intervensi.'},
'4.9':{steps:['Gunakan catatan pencerapan rekaan tanpa nama guru.','Asingkan pemerhatian, bukti dan tafsiran.','Jana maklum balas berdasarkan kekuatan dan satu keutamaan penambahbaikan.','Bina tiga soalan refleksi serta tindakan susulan.','Semak nada supaya profesional, spesifik dan tidak menghukum.'],prompt:'Tukarkan catatan pencerapan PdP berikut kepada maklum balas profesional. Asingkan Bukti Pemerhatian, Kekuatan, Keutamaan Penambahbaikan, Tiga Soalan Refleksi dan Pelan Susulan. Jangan mereka perkara yang tidak dicatat. Gunakan bahasa membina dan lindungi identiti guru. Catatan: [TAMPAL CATATAN REKAAN].',result:'Rumusan pencerapan dan rekod perbincangan susulan.'},
'5.1':{steps:['Muat turun dataset kehadiran Kelas 5 Bestari.','Audit struktur, nilai kosong, pendua dan status kehadiran.','Kira KPI dan ringkasan harian menggunakan definisi yang diberikan.','Bina dua carta dan dashboard satu halaman.','Audit semua angka dengan helaian Dashboard Contoh.'],prompt:'Analisis workbook kehadiran yang dimuat naik. Audit kualiti data, kira Kadar Kehadiran dan Kadar Tepat Masa, kenal pasti hari kritikal dan hasilkan spesifikasi dashboard. Bezakan dapatan, tafsiran dan cadangan. Jangan ubah nilai sumber.',result:'Dashboard kehadiran yang telah diaudit.',link:'latihan-analisis-kehadiran.html'},
'5.2':{steps:['Muat turun dataset prestasi akademik rekaan.','Semak mata pelajaran, kelas, pentaksiran dan nilai hilang.','Bandingkan pencapaian mengikut kelas dan mata pelajaran.','Kenal pasti jurang terbesar serta perubahan antara pentaksiran.','Sediakan ringkasan pengurusan dengan tiga tindakan berkeutamaan.'],prompt:'Analisis dataset prestasi akademik sekolah yang dimuat naik. Semak kualiti data, bandingkan kelas, mata pelajaran dan pentaksiran, kemudian kenal pasti jurang serta pola. Hasilkan jadual dapatan, carta yang sesuai dan tiga cadangan tindakan. Jangan membuat kesimpulan sebab-akibat.',result:'Laporan prestasi dan cadangan tindakan.'},
'5.3':{steps:['Muat turun dataset soal selidik rekaan.','Semak skala respons, nilai kosong dan soalan terbuka.','Kira ringkasan setiap item dan kelompokkan komen mengikut tema.','Bezakan komen dominan daripada komen terpencil.','Bina pelan respons sekolah dan mesej maklum balas kepada ibu bapa.'],prompt:'Analisis dataset soal selidik ibu bapa. Ringkaskan skor setiap item, kelompokkan komen kepada tema, nyatakan kekerapan dan pilih petikan tanpa identiti. Bezakan dapatan kuantitatif dan kualitatif. Cadangkan pelan respons sekolah dengan pegawai, tempoh dan ukuran kejayaan.',result:'Analisis kepuasan dan pelan respons sekolah.'},
'5.4':{steps:['Pilih satu dapatan yang telah disahkan.','Nyatakan masalah, sasaran dan hasil yang hendak dicapai.','Jana aktiviti, pegawai, tempoh, sumber dan KPI.','Semak risiko, kebergantungan dan bukti kemajuan.','Tetapkan tarikh semakan serta kaedah pelaporan.'],prompt:'Tukarkan dapatan berikut kepada pelan tindakan sekolah. Susun jadual Isu | Objektif | Aktiviti | Pegawai | Tarikh | Sumber | KPI | Bukti | Risiko | Status. Gunakan cadangan yang realistik untuk sekolah rendah dan tandakan maklumat yang perlu ditentukan oleh pentadbir. Dapatan: [TAMPAL DAPATAN].',result:'Pelan tindakan sekolah yang boleh dipantau.'},
'5.5':{steps:['Cipta notebook khusus untuk satu pekeliling.','Muat naik dokumen rasmi dan semak status pemprosesan.','Tetapkan arahan supaya jawapan menggunakan sumber sahaja.','Ekstrak tujuan, sasaran, tarikh, tanggungjawab dan dokumen sokongan.','Sahkan setiap perkara melalui petikan dan halaman sumber.'],prompt:'Berdasarkan pekeliling dalam notebook sahaja, bina jadual Perkara | Maklumat Penting | Tindakan Sekolah | Pegawai | Tarikh | Dokumen Sokongan | Sumber dan Halaman. Jika maklumat tiada, tulis “Tidak dinyatakan dalam sumber”.',result:'Ringkasan pekeliling dan senarai tindakan.'},
'5.6':{steps:['Kumpulkan dokumen rasmi berkaitan skim perkhidmatan pendidikan.','Muat naik sumber dan asingkan mengikut jenis dokumen.','Bina inventori gred, syarat dan laluan kerjaya dengan rujukan.','Hasilkan FAQ menggunakan istilah yang tepat.','Audit semua dakwaan sebelum menerbitkan panduan.'],prompt:'Gunakan sumber notebook sahaja untuk membina panduan Skim Perkhidmatan Pendidikan. Sertakan jadual gred, syarat, laluan kerjaya, istilah penting dan FAQ. Letakkan rujukan sumber bagi setiap fakta dan nyatakan jika sesuatu perkara tidak dapat disahkan.',result:'Panduan skim perguruan berasaskan sumber.',link:'latihan-gemini-notebook-skim-pendidikan.html'},
'5.7':{steps:['Muat naik pekeliling, SOP dan garis panduan yang masih berkuat kuasa.','Labelkan setiap sumber mengikut bidang dan tarikh.','Bina kategori soalan untuk kurikulum, HEM, keselamatan dan pentadbiran.','Jana FAQ serta senarai semak dengan rujukan.','Uji lima soalan sebenar dan baiki jawapan yang kabur.'],prompt:'Bina pusat rujukan polisi sekolah berdasarkan sumber notebook sahaja. Susun mengikut kategori, hasilkan FAQ dan senarai semak tindakan, serta sertakan nama sumber dan halaman. Jika dokumen bercanggah, tunjukkan percanggahan tanpa memilih satu jawapan secara sendiri.',result:'Pusat soal jawab polisi sekolah yang boleh diaudit.'},
'5.8':{steps:['Muat naik minit mesyuarat dan analisis prestasi yang dinyahidentiti.','Ekstrak keputusan, isu, tindakan, pegawai dan tarikh.','Padankan setiap tindakan dengan dapatan data atau bukti dokumen.','Bina laporan mesyuarat dan agenda susulan.','Semak bahawa tiada keputusan baharu dicipta oleh AI.'],prompt:'Gabungkan minit mesyuarat dan analisis prestasi dalam notebook. Hasilkan laporan dengan bahagian Dapatan, Keputusan Mesyuarat, Tindakan, Pegawai, Tarikh Akhir, Bukti dan Status. Jangan cipta keputusan atau pegawai yang tidak dinyatakan.',result:'Laporan mesyuarat dan daftar tindakan susulan.'},
'5.9':{steps:['Gunakan dataset rekaan kehadiran, prestasi dan disiplin.','Tetapkan kriteria risiko bersama pasukan HEM.','Kira tahap risiko secara telus dan senaraikan faktor yang menyumbang.','Cadangkan intervensi mengikut tahap risiko.','Semak kes secara manusia dan tetapkan tarikh pemantauan.'],prompt:'Berdasarkan data rekaan yang dimuat naik dan kriteria risiko [KRITERIA], bina sistem amaran awal murid. Paparkan ID rekaan, faktor risiko, tahap, bukti, tindakan, pegawai dan tarikh semakan. Jangan membuat diagnosis atau keputusan automatik.',result:'Daftar risiko dan pelan intervensi yang disemak manusia.'},
'5.10':{steps:['Muat naik garis panduan keselamatan dan laporan pemeriksaan rekaan.','Bina senarai kriteria pematuhan daripada sumber.','Bandingkan setiap pemerhatian dengan kriteria tersebut.','Kelaskan risiko dan cadangkan mitigasi mengikut keutamaan.','Sahkan tindakan dengan jawatankuasa keselamatan.'],prompt:'Audit laporan pemeriksaan sekolah terhadap garis panduan dalam notebook. Hasilkan jadual Lokasi | Pemerhatian | Keperluan Sumber | Status | Tahap Risiko | Mitigasi | Pegawai | Tempoh | Rujukan. Jangan tambah syarat yang tiada dalam sumber.',result:'Daftar risiko dan pelan mitigasi keselamatan.'},
'5.11':{steps:['Senaraikan domain penilaian dan bukti yang diperlukan.','Muat naik dokumen bukti yang telah diluluskan.','Peta bukti kepada setiap indikator.','Kenal pasti indikator tanpa bukti atau bukti tidak mencukupi.','Bina matriks penambahbaikan dan tarikh semakan.'],prompt:'Berdasarkan indikator dan sumber notebook, bina matriks penilaian kendiri sekolah: Indikator | Bukti | Status | Kekuatan | Jurang Bukti | Tindakan | Pemilik | Tarikh. Jangan memberikan skor jika kaedah penskoran tidak terdapat dalam sumber.',result:'Matriks penilaian kendiri berasaskan bukti.'},
'5.12':{steps:['Gunakan senario insiden rekaan tanpa identiti murid.','Muat naik polisi perlindungan dan prosedur pelaporan rasmi.','Kenal pasti tindakan segera, pelaporan dan dokumentasi.','Susun aliran eskalasi serta tindakan susulan.','Minta pegawai berautoriti menyemak sebelum latihan simulasi.'],prompt:'Berdasarkan polisi dalam notebook dan senario rekaan berikut, bina pelan pengurusan insiden. Asingkan tindakan segera, keselamatan murid, pihak yang perlu dimaklumkan, dokumentasi, eskalasi dan susulan. Sertakan rujukan sumber. Jangan membuat andaian undang-undang atau mendedahkan identiti.',result:'Pelan tindakan insiden dan aliran pelaporan.'},
'5.13':{steps:['Senaraikan data operasi yang diperlukan setiap hari.','Gunakan data rekaan bagi kehadiran, guru ganti, program dan aduan.','Takrifkan KPI, ambang perhatian dan pemilik tindakan.','Bina susun atur dashboard serta ringkasan pagi.','Audit angka, akses pengguna dan proses kemas kini.'],prompt:'Reka dashboard operasi harian sekolah menggunakan data rekaan yang dimuat naik. Sertakan KPI kehadiran, guru ganti, program hari ini, aduan kemudahan dan tindakan segera. Bina jadual Isu | Keutamaan | Pegawai | Tarikh | Status serta ringkasan pagi maksimum 150 patah perkataan.',result:'Dashboard operasi dan ringkasan tindakan harian.'}
};

document.querySelectorAll('.training-card').forEach(card=>{
  const code=card.querySelector('.training-tag')?.textContent.trim();
  const guide=trainingGuides[code];
  if(!guide||card.querySelector('.guided-steps'))return;
  const details=document.createElement('details');details.className='guided-steps';details.open=card.classList.contains('featured');
  details.innerHTML='<summary>Langkah demi langkah</summary><ol class="steps">'+guide.steps.map(x=>'<li>'+x+'</li>').join('')+'</ol><div class="prompt-box"><div class="prompt-top"><strong>Prompt latihan</strong><button class="copy-guide" type="button">Salin prompt</button></div><p class="prompt-text"></p></div><div class="result-line"><strong>Hasil:</strong> '+guide.result+'</div>'+(guide.link?'<a class="more" href="'+guide.link+'">Buka panduan lengkap →</a>':'');
  details.querySelector('.prompt-text').textContent=guide.prompt;
  card.appendChild(details);
});

document.querySelectorAll('.copy-guide').forEach(btn=>btn.addEventListener('click',async()=>{const text=btn.closest('.prompt-box').querySelector('.prompt-text').innerText;await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='✓ Disalin';setTimeout(()=>btn.textContent=old,1800)}));
